SELECT * FROM employee;
SELECT ename FROM employee;
SELECT ename, sal FROM employee;
SELECT ename, comm FROM employee;
SELECT empno, deptno FROM employee;
SELECT ename, hiredate FROM employee;
SELECT ename, job FROM employee;
SELECT ename, job, sal FROM employee;
SELECT dname FROM department;
SELECT dname, loc FROM department;
SELECT ename, sal*12 AS annual_salary FROM employee;
SELECT ename, job, sal*6 AS half_term_salary FROM employee;
SELECT *, sal*12 + 2000 AS annual_bonus FROM employee;
SELECT ename, sal, sal + (sal*0.10) AS hike_salary FROM employee;
SELECT ename, sal, sal - (sal*0.25) AS deducted_salary FROM employee;
SELECT ename, sal, sal + 50 AS monthly_hike FROM employee;
SELECT ename, sal*12 - (sal*12*0.10) AS annual_after_deduction FROM employee;
SELECT ename, sal + IFNULL(comm,0) AS total_salary FROM employee;
SELECT *, sal*12 AS annual_salary FROM employee;
SELECT ename, job, sal - 100 AS penalized_salary FROM employee;
